[package]
name = "snake_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn_array = "0.1.6"
rand = "0.8.5"
crossterm = "0.24.0"
